services:
  - docker:stable
before_script:
  - docker info

build_image:
  script:
    - docker build -t my-docker-image .
    - docker run my-docker-image /script/to/run/tests

build:
  services:
    - docker:stable
  stage: deploy
  script:
    - docker build -t errbot 
    - pip install awscli
  script:
    - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include ""
  