
image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

stages:
  - deploy

to-production:
  only:
    - master
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker info
    - docker build -terrbot
    - pip install awscli
  script:
    - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include ""
  