image: docker:stable

before_script:
  - sleep $[($RANDOM % 2) + 5]
  - docker info

build_image:
  stage: deploy
  before_script:
    - docker build -terrbot ./
    - pip install awscli
  script:
    - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include ""
