image: docker:stable

services:
  - docker:dind
before_script:
  - docker info

build_image:
  services:
    - docker:dind
  stage: deploy
  before_script:
    - docker build -t errbot 
    - pip install awscli
  script:
    - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include ""
