
image: python:3


stages:
  - deploy

to-production:
  only:
    - master
  stage: deploy
  before_script:
    - docker info
    - docker build -terrbot
    - pip install awscli
  script:
    - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include ""
  