services:
  - docker:stable
before_script:
  - docker info

build_image:
  services:
    - docker:stable
  stage: deploy
  befor_script:
    - docker build -t errbot 
    - pip install awscli
  script:
    - aws s3 cp ./ s3://yourbucket/ --recursive --exclude "*" --include ""
