intents:
    - order_pizza
    - greet
    - pedant
    - goodby
    - illness

entities:
    - size
    - toppings
    - correction
    - first
    - last

slots:
    size:
        type: text
    toppings:
        type: text
    correction:
        type: text
    first:
        type: text
    last:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_get_pizza_size:
        - 'What pizza size?'
    utter_get_pizza_toppings:
        - 'What toppings would you like on your pizza?'
    utter_goodby:
        - 'See you later'
        - 'Bye'
    utter_get_illnes_first:
        - What is the first day of your illness
    utter_get_illnes_last:
        - What is the last day of your illness

actions:
    - utter_goodby
    - utter_greet
    - utter_get_pizza_size
    - utter_get_pizza_toppings
    - actions.ActionOrderPizza
    - utter_get_illnes_first
    - utter_get_illnes_last
    - actions.ActionPedant
    - actions.ActionIllness