intents:
    - order_pizza
    - greet
    - pedant
    - goodby
entities:
    - size
    - toppings
    - correction

slots:
    size:
        type: text
    toppings:
        type: list
    correction:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_get_pizza_size:
        - 'What pizza size?'
    utter_get_pizza_toppings:
        - 'What toppings would you like on your pizza?'
actions:
    - utter_greet
    - utter_get_pizza_size
    - utter_get_pizza_toppings
    - actions.ActionOrderPizza
    - actions.ActionPedant