intents:
    - order_pizza
    - greet
    - pedant
    - goodby
    - report_illness_duration
    - report_illness_from_to

entities:
    - size
    - toppings
    - correction
    - first
    - last
    - duration

slots:
    user:
        type: unfeaturized
    size:
        type: text
    toppings:
        type: text
    correction:
        type: text
    first:
        type: text
    last:
        type: text
    duration:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_get_pizza_size:
        - 'What pizza size?'
    utter_get_pizza_toppings:
        - 'What toppings would you like on your pizza?'
    utter_goodby:
        - 'See you later'
        - 'Bye'
    utter_get_report_illness_from_to_first:
        - What is the first day of your illness
    utter_get_report_illness_from_to_last:
        - What is the last day of your illness
    utter_get_report_illness_duration_duration:
        - How long will you be away?

actions:
    - utter_goodby
    - utter_greet
    - utter_get_pizza_size
    - utter_get_pizza_toppings
    - actions.ActionOrderPizza
    - utter_get_report_illness_from_to_first
    - utter_get_report_illness_from_to_last
    - utter_get_report_illness_duration_duration
    - actions.ActionPedant
    - actions.ActionIllnessFromTo
    - actions.ActionIllnessDuration