intents:
    - greet
    - goodby
    - who_knows_topic
    - claim_to_know_topic
    - claim_to_know_topic_in_category
    - forgott_topic
    - topics_in_category
    - report_illness_duration
    - report_illness_from_to

entities:
    - category
    - topic
    - first
    - last
    - duration
    - time
    - number
    - confirmation

slots:
    topic:
      type: text
    category:
        type: categorical
        values:
            - sprachen
            - tools
            - technologien
            - agile
            - plattformen
    time:
        type: unfeaturized
    number:
        type: unfeaturized
    user:
        type: unfeaturized
    correction:
        type: text
    first:
        type: text
    last:
        type: text
    duration:
        type: text
    confirmation:
        type: categorical
        values:
            - confirmation_accepted
            - confirmation_declined
    auth_confirmation:
        type: categorical
        values:
            - auth_confirmed
            - auth_declined
    auth_required:
        type: bool
    confirmation_required:
        type: bool
    body:
        type: text
    subject:
        type: text

templates:
    utter_get_who_knows_topic:
        - Um welches Thema geht es?
    utter_get_who_knows_category:
        -  "In welche Kategorie würdest du es einsortieren?"
    utter_get_claim_to_know_topic:
        - Um welches Thema geht es?
    utter_get_claim_to_know_category:
        -  "In welche Kategorie würdest du es einsortieren?"
    utter_get_report_illness_last:
        - What is the last day of your illness
    utter_get_report_illness_duration:
        - How long will you be away?
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_goodby:
        - 'See you later'
        - 'Bye'

actions:
    - utter_goodby
    - utter_greet
    - utter_get_who_knows_category
    - utter_get_who_knows_topic
    - utter_get_claim_to_know_category
    - utter_get_claim_to_know_topic
    - actions.ActionWhoKnowsTopic
    - actions.ActionClaimToKnowTopic
    - actions.ActionIForgot
    - actions.ActionConfirmation
    - actions.ActionTopicsInCategory
    - utter_get_report_illness_last
    - utter_get_report_illness_duration
    - actions.ActionPreReportIllness
    - actions.ActionReportIllness