 language: "de"

 pipeline:
 - name: "nlp_spacy"
   model: "de"
 - name: "tokenizer_spacy"
 - name: "ner_crf"
 - name: "intent_featurizer_spacy"
 - name: "intent_classifier_sklearn"
 - name: "ner_duckling"
   dimension: ["first", "last", "duration", "time", "number"]